portal/super/forms.py
from flask_wtf.form import FlaskForm
from wtforms.fields import SubmitField, SelectField
from wtforms.validators import DataRequired
from ..auth.forms import BaseSignUp



class CreateAdmin(BaseSignUp, FlaskForm):
    """
    The form for creating admins, available only to super admins
    """
    position = SelectField(validators=[DataRequired()], choices=['--Position--', 'Dean', 'HOD', 'Senior Lecturer', 'Lecturer II', 'Lecturer I', 'Assistant Lecturer'])
    submit = SubmitField('CREATE')

portal/super/__init__.py
from flask import Blueprint

super = Blueprint('super', __name__)

from . import views, forms

portal/super/views.py
import secrets, string
from flask import render_template, redirect, flash, url_for, request, current_app
from . import super
from .. import db
from .forms import CreateAdmin
from ..decorators import role_required
from ..models import Admin



def generate_admin_id():
    """
    Custom function for generating admin IDs. Made as random as possible using Python's ``secrets`` module and an iteration through the current list to ensure IDs do not clash
    """
    def randomize():
        """
        Main function that generates the IDs
        """
        alphabet = string.ascii_lowercase
        numbers = string.digits
        first = ''.join(secrets.choice(alphabet) for i in range(5))
        second = ''.join(secrets.choice(string.digits) for i in range(5))
        return '{}_{}'.format(first, second)
      
    # list of all admin  user IDs
    admins = [admin.user_id for admin in Admin.query.all()]

    id = randomize()    
    # ensure a generated ID does not exist
    while True:
        if id in admins:
            id = randomize()
            continue
        break
    
    return id


@super.route('/super_admin/dashboard')
@role_required('super')
def home():
    """
    View for home page of the super admin.
    """
    return render_template('super/home.html')


@super.route('/super_admin/create-admin', methods=['GET', 'POST'])
@role_required('super')
def create_admin():
    """
    View function for creating a new admin. Redirects to itself after creating an admin successfully. Flash message to denote a successful creation.
    """
    create_admin = CreateAdmin()
    if create_admin.validate_on_submit():
        # create admin object
        admin = Admin(acc_role = 'admin',
                    first_name = create_admin.first_name.data, 
                    middle_name = create_admin.middle_name.data, 
                    last_name = create_admin.last_name.data,
                    user_id = generate_admin_id(),
                    position = create_admin.position.data,
                    password = create_admin.password.data)
        # add to database and commit
        try:
            db.session.add(admin)
            db.session.commit()
            flash('Admin created successfully. Activated by default.', 'info')
            return redirect(url_for('.create_admin'))
        # flash a message if an error occurs
        except:
            flash('An error occured, please try again.', 'error')
    return render_template('super/create_admin.html', create_admin = create_admin)


@super.route('/super_admin/manage-admins', methods=['GET', 'POST'])
@role_required('super')
def manage_admins():
    """
    View function for managing admins. Admins are simply activated and deactivated, no deletion.
    """
    # list of all available admins
    admins = Admin.query.all()

    if request.method == 'POST':
        """
        After form is submitted(changes applied), all checked boxes are retrieved and admins whose ID's are seen are activated, else deactivated.
        """
        # list of all checked checkboxes
        ids = request.form.getlist('activated')
        # holds list of admins that were activated in form
        active_list = [Admin.query.get(id) for id in ids]

        # loop through admins and check against new list of active admins
        for admin in admins:
            # if found in new list, set active status to True
            if admin in active_list:
                admin.active_status = True
            # otherwise, set to False
            else:
                admin.active_status = False
            current_app.logger.info('{} - {}'.format(admin.first_name, admin.active_status))
            db.session.add(admin)
        db.session.commit()
        flash('Changes applied successfuly!', 'info')
        return redirect(url_for('.manage_admins'))
    return render_template('super/manage_admins.html', admins = admins)

portal/templates/super/create_admin.html
{% extends "base.html" %}

{% block title %}Create Admin{% endblock %}

{% block body %}

<div class="main">
    <!-- CREATE ADMINS -->
{% if current_user.acc_role == 'super' %}
    <form action="" method="POST">
        {% for categ, msg in get_flashed_messages(with_categories=True) %}
        <div class="flash">
            <li style="list-style: none;" class="{{ categ }}">{{ msg }}</li>
        </div>
        {% endfor %}
        
        {{ create_admin.hidden_tag() }}

        <div class="form-group">
            {{ create_admin.first_name(placeholder='First Name') }}
        </div>
        
        <div class="form-group">
            {{ create_admin.middle_name(placeholder='Middle Name') }}
        </div>

        <div class="form-group">
            {{ create_admin.last_name(placeholder='Last Name') }}
        </div>

        <div class="form-group">
            {{ create_admin.position(placeholder='Position') }}
        </div>

        <div class="form-group">
            {{ create_admin.password(placeholder='Password') }}
        </div>

        <div class="form-group">
            {{ create_admin.password2(placeholder='Confirm Password') }}
        </div>

        <div class="form-group">
            {{ create_admin.submit(class='green-hov') }}
        </div>
    </form>
{% endif %}

    <a class="link-btn" href="{{ url_for('super.home') }}">⬅ Go back</a>
</div>

{% endblock %}

portal/templates/super/home.html
{% extends "base.html" %}

{% block title %}Super Admin Home{% endblock %}

{% block body %}

<div class="main">
    <div class="title">{{ current_user.user_id }}</div>
    <p><a href="{{ url_for('auth.logout') }}">Log Out</a></p>

    <div class="sub">
        <!-- CREATE ADMINS -->
        <a class="link-btn" href="{{ url_for('super.create_admin') }}">Create Admin</a>


        <!-- MANAGE ADMINS -->
        <a class="link-btn" href="{{ url_for('super.manage_admins') }}">Manage Admins</a>


        <!-- FORM TO FIND LECTURERS AND STUDENTS -->
        <a class="link-btn" href="#">Other Admin Functions</a>    
    </div>
    
</div>

{% endblock %}

portal/templates/super/manage_admins.html
{% extends "base.html" %}

{% block title %}Manage Admins{% endblock %}

{% block body %}

<div class="main">
{% if current_user.acc_role == 'super' %}

    <form action="{{ url_for('super.manage_admins') }}" method="POST">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>

        <table>
            <thead>
                <tr>
                    <th>Admin ID</th>
                    <th>Name</th>
                    <th>Creation Date</th>
                    <th>Active Status</th>
                </tr>
            </thead>
            
            <tbody>
                {% for admin in admins %}
                <tr>
                    <td>{{ admin.user_id }}</td>
                    <td>{{ admin.first_name }} {{ admin.middle_name }} {{ admin.last_name }}</td>
                    <td>{{ admin.creation_date }}</td>

                    <td>
                        {% if admin.active_status %}
                        <input type="checkbox" name="activated" value="{{admin.user_id}}" checked>
                        {% else %}
                        <input type="checkbox" name="activated" value="{{admin.user_id}}">
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <input type="submit" value="Apply Changes" class="green-hov">
    </form>

    {% for categ, msg in get_flashed_messages(with_categories=True) %}
    <div class="flash">
        <li style="list-style: none;" class="{{ categ }}">{{ msg }}</li>
    </div>
    {% endfor %}
    
{% endif %}

    <a class="link-btn" href="{{ url_for('super.home') }}">⬅ Go back</a>
</div>

{% endblock %}